### ISSUE TITLE
RuntimeError: Expected to have finished reduction in the prior iteration before starting a new one. This error indicates that your module has parameters that were not used in producing loss.

### ISSUE THREAD

**Issue by vamckrish32** [microsoft/Cream#197] opened 2023-11-07 06:44 UTC
RuntimeError: Expected to have finished reduction in the prior iteration before starting a new one. This error indicates that your module has parameters that were not used in producing loss. You can enable unused parameter detection by passing the keyword argument `find_unused_parameters=True` to `torch.nn.parallel.DistributedDataParallel`, and by
making sure all `forward` function outputs participate in calculating loss.
If you already have done the above, then the distributed data parallel module wasn't able to locate the output tensors in the return value of your module's `forward` function. Please include the loss function and the structure of the return value of `forward` of your module when reporting this issue (e.g. list, dict, iterable).
Parameter indices which did not receive grad for rank 0: 138 139 142 143 144 145
 In addition, you can set the environment variable TORCH_DISTRIBUTED_DEBUG to either INFO or DETAIL to print out information about which particular parameters did not receive gradient on this rank as part of this error

**Comment by wkcn** [comment] 2023-11-08 01:39
Hi @vamckrish32 , thanks for your attention to our work!

Could you please tell me which project raised the error, and how to reproduce it?

**Comment by vamckrish32** [comment] 2023-11-09 05:56
hi 
I am getting this error from Tiny Clip pre training code 
By running this command
"sh script/auto_weight_inherit_100to75.sh"

**Comment by wkcn** [comment] 2023-11-09 17:36
Thank @vamckrish32 ! I will check it.

**Comment by wkcn** [comment] 2023-11-09 17:56
Sorry that I could not reproduce the error.

I need more details.
1. At which iteration did the error occur?
2. How many GPUs did you use, and what is the value of the `--prune-step`?
3. What is your PyTorch version? The version of PyTorch I used is 1.11.0. You could try updating it to 1.11 or later.

Thank you!

**Comment by wkcn** [comment] 2023-11-23 15:37
Close it. Feel free to reopen it if the issue still exists. : )

**Comment by Gumpest** [comment] 2024-01-08 16:26
@wkcn Sorry, I encountered the same problem.

**Comment by wkcn** [comment] 2024-01-09 03:09
@Gumpest Thanks for your attention to our work!

Which version of PyTorch did you use? You could try updating PyTorch to 1.11 or the newer version.

**Comment by Gumpest** [comment] 2024-01-09 03:43
@wkcn Thanks for your reply. The version of PyTorch is 2.1.2.
<img width="927" alt="image" src="https://github.com/microsoft/Cream/assets/56063339/af652fe8-175e-4d85-807c-e48d34d1000c">

**Comment by Gumpest** [comment] 2024-01-09 03:45
1. At which iteration did the error occur? `The initial step.`
2. How many GPUs did you use, and what is the value of the --prune-step? `3 A100 80GB and utilize auto_weight_inherit_100to75.sh.`

**Comment by Gumpest** [comment] 2024-01-09 03:50
<img width="946" alt="image" src="https://github.com/microsoft/Cream/assets/56063339/6df75b2b-34c9-4cbc-9df3-97a4f3bca3b8">

**Comment by Gumpest** [comment] 2024-01-09 04:56
By the way, if I change `L476` to the `torch.nn.parallel.DistributedDataParallel, device_ids=[device], find_unused_parameters=True, **ddp_args)`, it will `Expected to mark a variable ready only once.  `

**Comment by wkcn** [comment] 2024-01-09 06:34
@Gumpest Thank you for pointing it out! I will check it on PyTorch 2.1.2.

**Comment by Gumpest** [comment] 2024-01-09 06:54
@wkcn Thanks a lot! Wait for your solution. 🙏

**Comment by wkcn** [comment] 2024-01-11 09:08
Hi @Gumpest and @vamckrish32 , I have fixed the bug on PyTorch 2.0+ in the latest code of TinyCLIP.

**Closed** 2024-01-12 01:15 UTC
Labels: bug, TinyCLIP
